[project]
name = "core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "sqlalchemy>=2.0.36",
    "pydantic-settings>=2.6.0",
    "pydantic[email]>=2.9.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
