[project]
name = "functionality1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
functionality1 = "functionality1:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
