name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python
      - run: bin/lint
